version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: firmable_postgres
    environment:
      POSTGRES_USER: firmable
      POSTGRES_PASSWORD: firmablepass
      POSTGRES_DB: firmabledb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
